apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: kubeflow
resources:
  - crds/
  - cluster-role-binding.yaml
  - cluster-role.yaml
  - service-account.yaml
  - service.yaml
  - deployment.yaml
images:
  - name: kubeflow/training-operator
    newName: public.ecr.aws/j1r0q0g6/training/training-operator
    newTag: "5ef6c405df2bb1bf1d3ede988cd43433eff2e956"
