apiVersion: v1
kind: Pod
metadata:
  name: access-model
spec:
  containers:
  - name: model-storage
    image: alpine:latest
    command: ['sleep', 'infinity']
    volumeMounts:
    - name: model
      mountPath: /trained_model
  volumes:
  - name: model
    persistentVolumeClaim:
      claimName: strategy-volume
